version: '3.1'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpw
      POSTGRES_DB: vidaemcorrotinadb
